"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ros_to_lcm(object):
    __slots__ = ["timezz"]

    __typenames__ = ["int64_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.timezz = 0

    def encode(self):
        buf = BytesIO()
        buf.write(ros_to_lcm._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timezz))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ros_to_lcm._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ros_to_lcm._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ros_to_lcm()
        self.timezz = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if ros_to_lcm in parents: return 0
        tmphash = (0x89a8b8ee4797d9ee) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ros_to_lcm._packed_fingerprint is None:
            ros_to_lcm._packed_fingerprint = struct.pack(">Q", ros_to_lcm._get_hash_recursive([]))
        return ros_to_lcm._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ros_to_lcm._get_packed_fingerprint())[0]

